name: PR maintenance

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited    

permissions:
  pull-requests: write
  actions: write

jobs:
  maintenance:
    if: startsWith(github.event.pull_request.title, 'Bump ') && startsWith(github.event.pull_request.head.ref, 'pr1')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - run: |
          gh pr edit ${{ github.event.pull_request.number}} --title '$(echo "${{github.event.pull_request.title}}" | sed "s/Bump /chore: bump /")'
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
# gh workflow run lint-commit-message.yml --ref ${{ github.event.pull_request.head.ref }}