name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]
permissions:
  actions: 'write'
jobs:
  release-pull-request:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.commit-subject.outputs.skip }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git log -n 1 --pretty=%s 
      - name: Check last commit subject
        id: commit-subject
        run: |
          git log -n 1 --pretty=%s | grep "chore(release):" -v && echo 1
      # - name: Early exit
      #   if: ${{ steps.commit-subject.outputs.skip }} == 1
      #   run: |
      #     gh run cancel ${{ github.run_id }}
      #     gh run watch ${{ github.run_id }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Setup Versionize
        run: |
          dotnet tool install --global Versionize
      - name: Bump version
        run: |
          versionize --pre-release pre --proj-version-bump-logic --skip-commit --aggregate-pre-releases
      - name: Get current version
        id: get-current-version
        run: |
          echo "version=$(versionize inspect)" >> $GITHUB_OUTPUT
      - name: Create release Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            chore(release): ${{ steps.get-current-version.outputs.version }}
          title: |
            chore(release): ${{ steps.get-current-version.outputs.version }}
          body: |
            This is an automated pull request to release a new version of the package.
            Please review and merge if everything looks good.
          branch: release/${{ steps.get-current-version.outputs.version }}
          branch-suffix: short-commit-hash
          delete-branch: true
          labels: release
          draft: false
          signoff: false

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v3
      # - run: |
      #     dotnet install --global Versionize 
