name: PR maintenance

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - if: startsWith(github.event.pull_request.title, 'Bump ') && startsWith(github.event.pull_request.head.ref, 'pr1')
        run: |
          echo "special processing"
          gh pr edit ${{ github.event.pull_request.number}} --title "chore: ${{github.event.pull_request.title}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}