name: PR maintenance

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - if: startsWith(github.event.pull_request.title, 'Bump ')
        run: echo "special processing"
      - name: github.event.pull_request.base.ref
        run: |
          echo ${github.event.pull_request.base.ref}
      - name: github.event.pull_request.target.ref
        run: |
          echo ${github.event.pull_request.target.ref}